export const SUPABASE_URL = import.meta.env?.VITE_SUPABASE_URL || '';
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || '';

function parsePrivateLines(value) {
  return String(value || '')
    .split('||')
    .map((line) => line.trim())
    .filter(Boolean);
}

export const IS_PRIVATE_BUILD =
  (import.meta.env?.VITE_WITHIN_REACH_BUILD === 'private' ||
    import.meta.env?.VITE_PRIVATE_BUILD === 'true' ||
    import.meta.env?.MODE === 'private') &&
  import.meta.env?.VITE_ENABLE_PRIVATE_BUILD === 'true';
export const ENABLE_SECRET_SECTION =
  IS_PRIVATE_BUILD && import.meta.env?.VITE_ENABLE_SECRET_SECTION !== 'false';

export const ENABLE_FUNNY_FACTS = true;
export const ARRIVAL_REVEAL_DELAY_MS = 2600;
export const MAX_NOTE_LENGTH = 300;
export const DEBUG_UI_MESSAGES = false;

export const ACCENT_BY_USER = {
  joey: '#678a5b',
  jeszi: '#8661a9',
};

export const GREETING_BY_USER = {
  joey: 'Hey Joey;',
  jeszi: 'Hey Jeszi;',
};

export const AMBIENT_LINES_SHARED = [
  'You found your way back here.',
  'A little signal made it through.',
  'This space was waiting.',
  'A quiet check-in arrived.',
  'You made it back.',
  'A familiar stop.',
  'Someone was thinking of you.',
  'A small place to pause.',
  'Another little thread held.',
  'Something gentle made its way here.',
  'This corner kept its light on.',
  'A small return.',
  'You reached the quiet part.',
  'A little trace of someone is here.',
  'Still, here you are.',
];

export const AMBIENT_LINES_PERSONALIZED = {
  joey: [
    'Jeszi left room for you here.',
    'A familiar signal found you.',
    'Something soft was waiting on the other side.',
    'You made your way back to her corner.',
    'A quiet thread pulled you here.',
  ],
  jeszi: [
    'Joey left room for you here.',
    'A familiar signal found you.',
    'Something soft was waiting on the other side.',
    'You made your way back to this little corner.',
    'A quiet thread pulled you here.',
  ],
};

export const ENV_PRIVATE_ARRIVAL_LINES = {
  joey: parsePrivateLines(import.meta.env?.VITE_PRIVATE_ARRIVAL_LINES_JOEY),
  jeszi: parsePrivateLines(import.meta.env?.VITE_PRIVATE_ARRIVAL_LINES_JESZI),
};

export const LANDING_SECONDARY_LINE_WEIGHTING = {
  none: 0.1,
  shared: 0.65,
  personal: 0.18,
  secret: 0.07,
};

export const ARRIVAL_AMBIENT_LINE_WEIGHTING = {
  shared: 0.45,
  personal: 0.35,
  private: 0.2,
};

export const SECRET_CLUE_FRAGMENT_CHANCE = 0.05;
export const SECRET_CLUE_FRAGMENTS = [
  'not everything here says its name.',
  'some quiet doors look like endings.',
  'one part of this place remembers you.',
  'something here is waiting in the margins.',
];
export const HIDDEN_LETTER_PATH = './kept.html';

export const FUNNY_FACTS_SHARED = {
  outOfTheBox: [
    'Sea otters have favorite rocks.',
    'Some cats are allergic to humans.',
    'A cloud can weigh more than a million pounds.',
    'Rats laugh when they are tickled.',
    'Honeybees can recognize human faces.',
    'There are mushrooms that glow in the dark.',
    'Sea otters hold hands so they do not drift apart.',
    "A shrimp's heart is in its head.",
    'Butterflies can taste with their feet.',
    'Cows tend to have best friends.',
    'Bananas are berries, botanically.',
    'Strawberries are not true berries, botanically.',
    'Honey can stay good for an extremely long time when stored well.',
    'A single strand of spaghetti is called a spaghetto.',
    'LEGO bricks from the 1950s can still fit modern bricks.',
    'Rubber bands last longer when refrigerated.',
    'Some metals react so strongly with water that they can catch fire.',
    'A day on Earth is very slowly getting longer.',
    'The Eiffel Tower can grow a little taller in warm weather.',
    'Peanuts are legumes, not nuts.',
    'Cashews grow from the bottom of cashew apples.',
    'Carrots were not always orange.',
    'There are clocks that use atoms to keep time.',
    'A bolt of lightning can be hotter than the surface of the sun.',
    'Bubble wrap was originally pitched as wallpaper.',
    'The tiny pocket in jeans was originally made for pocket watches.',
    'Apples float because they are partly air.',
    'Some beaches are made partly from parrotfish sand.',
    'Pineapples are made of many small fruitlets fused together.',
    'Hot water can sometimes freeze faster than cold water.',
    'There is a word for the day after tomorrow: overmorrow.',
    'A jiffy is a real unit in some scientific contexts.',
    'Some turtles can breathe through their butts.',
    'Snow has fallen in the Sahara Desert.',
    'The smell of old books comes from paper and ink slowly breaking down.',
    'Glass is not really a slow liquid, which ruins a good rumor.',
    'Flamingos are sometimes called a flamboyance.',
    'Some sand is magnetic.',
    'The same water has been cycling around Earth for a very long time.',
    'A flamingo has to eat with its head upside down.',
  ],
  animalOddities: [
    'Octopuses have three hearts.',
    'Koalas have fingerprints very similar to humans.',
    'Sloths can hold their breath longer than dolphins.',
    'Wombats make cube-shaped poop.',
    'Crows can remember human faces.',
    'Some frogs freeze and thaw back out later.',
    'Elephants can recognize themselves in mirrors.',
    'Penguins sometimes propose with pebbles.',
    'Dolphins use signature whistles a bit like names.',
    'Ladybugs can smell with their feet.',
    'Male seahorses give birth.',
    'Axolotls can regrow limbs.',
    'Platypuses lay eggs and produce milk.',
    'Platypuses can sense electric fields.',
    "A narwhal's tusk is actually a tooth.",
    'Giraffes have the same number of neck bones as humans.',
    'Tigers have striped skin, not just striped fur.',
    'Dog nose prints are unique.',
    'Flamingos turn pink because of what they eat.',
    'Bats are the only mammals capable of sustained flight.',
    'Mantis shrimp have unusually complex vision.',
    'Starfish can regrow lost arms.',
    'Some sea cucumbers can eject their own organs.',
    'One kind of jellyfish can revert to an earlier life stage.',
    'Ants farm aphids like tiny livestock.',
    'Leafcutter ants grow fungus gardens.',
    'Ravens play games and solve problems.',
    'Goats have rectangular pupils.',
    'Sheep can recognize faces.',
    'Horses can sleep standing up.',
    'Giraffes sleep in very short stretches.',
    'Sharks can replace thousands of teeth in a lifetime.',
    'Hummingbirds can fly backward.',
    'Orcas have dialects within their pods.',
    'Crocodiles carry their babies gently in their mouths.',
    'Kangaroos have a very hard time walking backward.',
    'Polar bear skin is black under all that fur.',
    'Some frogs use their eyes to help swallow.',
    'Dragonflies are extremely successful hunters.',
    'Honeybees communicate through dances.',
    'Elephants appear to mourn their dead.',
    'Octopuses can taste with their arms.',
    'Squid have blue blood.',
    'Snakes smell with their tongues.',
    'Naked mole rats are unusually resistant to cancer.',
    'Bowerbirds decorate elaborate displays to impress mates.',
    'Capybaras often tolerate other animals sitting on them.',
    'Pigeons can be trained to distinguish written words.',
    'Some moths can jam bat sonar.',
    'A group of porcupines is called a prickle.',
  ],
  languageOddities: [
    'The dot over a lowercase i is called a tittle.',
    'Eavesdrop comes from standing under the eaves to overhear people.',
    'Bookkeeper is one of the few common words with three double letters in a row.',
    'The longest English word typed with only the top row is typewriter.',
    'Queue is mostly just one letter waiting politely.',
    'The word salary traces back to salt.',
    'Moonbow is a real word. It is a rainbow made by moonlight.',
    'Petrichor is the smell after rain.',
    'Apricity means the warmth of the sun in winter.',
    'Liminal used to belong mostly to thresholds before the internet got hold of it.',
    'Goodbye began as a shortened form of "God be with ye."',
    'Awful once meant full of awe.',
    'Nice once meant foolish.',
    'Girl once referred to a young person of any gender.',
    'Decimate originally meant to remove one in ten.',
    'Muscle comes from a word meaning little mouse.',
    'Quarantine comes from a forty-day period.',
    'Malaria comes from words meaning bad air.',
    'Disaster traces back to the idea of an unlucky star.',
    'Window comes from an old phrase meaning wind eye.',
    "Daisy comes from day's eye.",
    'Companion comes from the idea of sharing bread.',
    'Robot comes from a Czech word connected to forced labor.',
    'Karaoke means empty orchestra.',
    'Tsunami means harbor wave.',
    'A pangram uses every letter of the alphabet.',
    'The quick brown fox jumps over the lazy dog is a pangram.',
    'Strengths is one of the longest one-syllable English words.',
    'The ampersand used to be recited after the alphabet.',
    'Alphabet comes from alpha and beta.',
    'Set has an unreasonable number of meanings.',
    'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo is grammatical, unfortunately.',
    'Contronyms are words that can mean their own opposites.',
    'Cleave can mean to split apart or cling to.',
    'Sanction can mean to permit or to punish.',
    'Dust can mean to remove dust or apply it.',
    'Oversight can mean supervision or a mistake.',
    'Hippopotamus means river horse.',
    'Laconic comes from Laconia, the region around Sparta.',
    'Panic traces back to the god Pan.',
    'Helicopter splits as helico-pter, not heli-copter.',
    'Bluetooth is named after Harald Bluetooth.',
    'Emoji is Japanese and does not come from emotion.',
    'Meander comes from the name of a winding river.',
    'Serendipity comes from The Three Princes of Serendip.',
    'Lemniscate is the name of the infinity-symbol shape.',
    'Clue comes from clew, meaning a ball of thread.',
    'Nightmare once had more to do with a creature than bad dreams.',
    'Silly once had meanings closer to blessed or innocent.',
    'A mondegreen is a misheard lyric or phrase.',
  ],
  spaceAndScale: [
    'Sharks existed before trees.',
    'The light from the sun takes about eight minutes to reach Earth.',
    'Venus spins the opposite direction of most planets.',
    'A day on Venus is longer than its year.',
    'The North Star will not always be the North Star.',
    'Saturn would float in water if you had a bathtub large enough.',
    'The moon has moonquakes.',
    'A teaspoon of neutron star would weigh an absurd amount.',
    'There are more possible chess games than atoms in the observable universe.',
    'The universe is still expanding, which feels a little rude to certainty.',
    'Jupiter is large enough to hold all the other planets by volume.',
    'Mars has a volcano taller than Mount Everest.',
    'Mercury is closest to the sun, but Venus is hotter.',
    'Footprints on the moon can last for millions of years.',
    'There are more trees on Earth than stars in the Milky Way.',
    'The Milky Way and Andromeda are slowly moving toward each other.',
    'The sun is an ordinary star, which feels humbling and slightly unfair.',
    'More than a million Earths could fit inside the sun.',
    'A year on Mercury is only 88 Earth days.',
    'Neptune has extremely fast winds.',
    'Uranus rotates on its side.',
    "Saturn's rings are mostly ice.",
    'The moon is slowly moving away from Earth.',
    'Earth is not a perfect sphere.',
    'You are moving through space even when you feel very still.',
    'Light from some stars started traveling before humans existed.',
    'A total solar eclipse works because the sun and moon look nearly the same size from Earth.',
    'The sun turns mass into energy every second.',
    'Some planets may have diamond rain.',
    'Rogue planets can drift through space without a star.',
    'Some dead stars are smaller than cities.',
    'Black holes are not cosmic vacuum cleaners.',
    'The edge of the observable universe is a limit of light, not a wall.',
    'A light-year is a distance, not a time.',
    'The International Space Station orbits Earth about every 90 minutes.',
    'Astronauts can get a little taller in space.',
    'Mars has a canyon system far larger than the Grand Canyon.',
    'Saturn has a hexagon-shaped storm at its north pole.',
    'Some moons may have oceans under their ice.',
    'Tiny bits of space dust fall to Earth every day.',
  ],
  dryAsides: [
    'A surprising amount of life is held together by tiny rituals.',
    'Not every strange detail needs a larger lesson.',
    'Some facts arrive like trivia. Some arrive like evidence.',
    'The world keeps making odd little choices without consulting anyone.',
    'There is no reason a crow should feel this symbolic, and yet.',
    'Some details are too specific not to matter to somebody.',
    'The universe has a habit of being quietly excessive.',
    'A lot of existence is just unlikely things continuing anyway.',
    'The facts were not asked to be emotionally relevant, but here they are.',
    'A small oddity is still an oddity.',
    'Nature keeps leaving footnotes.',
    'This seems unnecessary, which is exactly why it belongs here.',
    'Nobody told moss it had to be subtle.',
    'Somewhere, a mushroom is making poor lighting choices.',
    'The moon remains committed to atmosphere.',
    'Crows know too much for birds that refuse to pay rent.',
    'The sea has always had suspiciously specific ideas.',
    'Every now and then, science sounds like a rumor with better paperwork.',
    'This is technically information.',
    'Some facts do not improve the room, but they do change it.',
    'The world is full of tiny administrative errors.',
    'There is comfort in a fact that asks nothing from you.',
    'Some things are only charming because they are useless.',
    'A footnote can still have main-character energy.',
    'This is not important, which is part of the relief.',
    'Several mysteries are just animals being themselves.',
    'The universe is large and poorly labeled.',
    'A lot of wonder is just scale with better lighting.',
    'This feels like something a crow would already know.',
    'Not every fact needs to carry a metaphor. This one might anyway.',
    'It is good to remember that weirdness is standard issue.',
    'A tiny fact can still take up residence.',
    'Oddly specific is a valid emotional category.',
    'The planet remains committed to bit work.',
    'Some knowledge is mostly decorative, and that is fine.',
    'Reality has a strong sense of texture.',
    'This detail has no business being this memorable.',
    'A strange little fact has entered the room politely.',
    'Some things survive by being hard to explain.',
    'The evidence suggests the world was assembled with personality.',
    'This is the kind of fact that waits by the window.',
    'Nature does not always choose the cleanest metaphor.',
    'The archive of small nonsense remains open.',
    'This is why the page keeps getting refreshed.',
    'There are worse uses of attention.',
    'The day now contains one more unnecessary truth.',
    'Some facts feel handwritten.',
    'The world is not more sensible at larger scales.',
    'We remain surrounded by tiny unreasonable miracles.',
    'The committee on normalcy has been overruled again.',
  ],
};

export const CHECK_IN_TEMPLATES = [
  '{name} was thinking of you.',
  'A little thought from {name}.',
  '{name} stopped by.',
  '{name} left a quiet check-in.',
  'A small signal from {name}.',
  '{name} found their way back here.',
  '{name} passed through here for a moment.',
  '{name} sent a little thought your way.',
  'A familiar check-in from {name}.',
  '{name} left a soft trace here.',
];

export const REACTIONS = ['❤️', '✨', '🥹', '🌙', '🐞', '🌸'];

export const FOOTER_LINES = [
  'Still here.',
  'Quietly kept.',
  'A place to return to.',
  'Held in small ways.',
  'Left open.',
  'Waiting softly.',
];

export const VAPID_PUBLIC_KEY = 'BBXgJE0ZgO2vqWiUVc8YNNlhEgu-jJvFIeywoyrZ7pBvvldjKRE2wGfwZyQxLj1ov3iYuFccj63Ly_5lx_jyjGc';
